import json

f = open("mapa-virtual.json")
bd = json.load(f)
f.close()

cidades = bd['cidades']
ligacoes = bd['ligacoes']

def listaLigacoes(c):
    conteudo = """
        <div class="w3-container">
            <ul class="w3-ul" style="width:50%">
    """
    for l in ligacoes:
        if l['origem'] == c['id']:
            conteudo += f"""
                <li>
                    <a href="/ligacoes/{l['id']}"> {l['origem']} -> {l['destino']}</a>
                </li>
            """
    conteudo += """
            </ul>
        </div>
    """
    return conteudo

for c in cidades:
    f = open('./paginasHTML/'+ str(c['id']) + '.html', 'w')
    pagHTML = f"""
    <html>
        <head>
            <title>{c['nome']}</title>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="stylesheet" href="/w3.css">
            <meta charset="utf-8"/>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h3>{c['nome']}</h3>
                </header>

                <div class="w3-container">
                    <table>
                        <tr>
                            <td><b>Nome</b></td> <td>{c['nome']}</td>
                        </tr>
                        <tr>
                            <td><b>População</b></td> <td>{c['população']}</td>
                        </tr>
                        <tr>
                            <td><b>Distrito</b></td> <td>{c['distrito']}</td>
                        </tr>
                        <tr>
                            <td><b>Descrição</b></td> <td>{c['descrição']}</td>
                        </tr>
                        <tr>
                            <td><b>Ligações</b></td>
                            <td> {listaLigacoes(c)}
                            </td>
                        </tr>
                    </table>
                </div>

                <footer class="w3-container w3-teal">
                    <h5> Generated by EMDApp::EngWeb2024 </h5>
                    <address>
                        <a href="/cidades">Voltar</a>
                    </address>
                </footer>
            </div>
        </body>
    </html>
    """
    f.write(pagHTML)
    f.close()


for l in ligacoes:
    f = open('./paginasHTML/'+ str(l['id']) + '.html', 'w')
    pagHTML = f"""
    <html>
        <head>
            <title>{l['origem']} -> {l['destino']}</title>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="stylesheet" href="/w3.css">
            <meta charset="utf-8"/>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h3>{l['origem']} -> {l['destino']}</h3>
                </header>

                <div class="w3-container">
                    <table>
                        <tr>
                            <td><b>Origem</b></td> <td>{l['origem']}</td>
                        </tr>
                        <tr>
                            <td><b>Destino</b></td> <td>{l['destino']}</td>
                        </tr>
                        <tr>
                            <td><b>Distância</b></td> <td>{l['distância']}</td>
                        </tr>
                    </table>
                </div>

                <footer class="w3-container w3-teal">
                    <h5> Generated by EMDApp::EngWeb2024 </h5>
                    <address>
                        <a href="/ligacoes">Voltar</a>
                    </address>
                </footer>
            </div>
        </body>
    </html>
    """
    f.write(pagHTML)
    f.close()