import json

f = open("mapa-virtual.json")
bd = json.load(f)
f.close()


def chaveOrd(c):
    return c['nome']

cidades = bd['cidades']
cidades.sort(reverse=False, key=chaveOrd)

ligacoes = bd['ligacoes']

def preHTML (titulo):
    return f"""
<!DOCTYPE html>
<html>
    <head>
        <title>{titulo}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="stylesheet" href="w3.css">
        <meta charset="utf-8"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h3>{titulo}</h3>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
"""

posHTML = """
                </ul>
            </div>

            <footer class="w3-container w3-teal">
                <h5> Generated by EMDApp::EngWeb2024 </h5>
                <address>
                    <a href="/"> Voltar </a>
                </address>
            </footer>
        </div>
    </body>
</html>
"""

#Cidades
conteudoCidades = ""

for c in cidades:
    conteudoCidades += f"""
                <li>
                    <a href="/cidades/{c['id']}"> {c['nome']}</a>
                </li>
"""

pagHTML_cidades = preHTML("Cidades") + conteudoCidades + posHTML

f = open('./paginasHTML/cidades.html', 'w')
f.write(pagHTML_cidades)
f.close()


#Ligações
conteudoLigacoes = ""

for l in ligacoes:
    conteudoLigacoes += f"""
                <li>
                    <a href="/ligacoes/{l['id']}"> {l['origem']} -> {l['destino']}</a>
                </li>
"""

pagHTML_ligacoes = preHTML("Ligações") + conteudoLigacoes + posHTML

f = open('./paginasHTML/ligacoes.html', 'w')
f.write(pagHTML_ligacoes)
f.close()