exports.paginaInicial = function(d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores e períodos</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-black">
                    <h1>Compositores e Períodos
                    </h1>
                    
                </header>
                <div>
                    <ul class="w3-ul">
                        <li> <a href="/compositores"> Compositores </a></li>
                        <li> <a href="/periodos"> Períodos </a></li>
                    </ul>
                </div>
                <footer class="w3-container w3-black">
                    <h5>Generated by EngWeb2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}


// COMPOSITORES ------------------------------------------------------------------------

exports.compositoresListPage = function(clist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-black">
                    <h1>Compositores
                    <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Nome</th>
                            <th>Actions</th>
                        </tr>
                `
    for(let i=0; i < clist.length ; i++){
        pagHTML += `
                <tr>
                    <td>${clist[i].id}</td>
                    <td>
                        <a href="/compositores/${clist[i].id}">
                            ${clist[i].nome}
                        </a>
                    </td>
                    <td>
                        [<a href="/compositores/edit/${clist[i].id}">Edit</a>][<a href="/compositores/delete/${clist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-black">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/">Voltar</a>]</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}


exports.compositoresByPeriodo = function(clist, periodo, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores do Período ${periodo}</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-black">
                    <h1>Compositores do Período ${periodo}
                    <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Nome</th>
                            <th>Actions</th>
                        </tr>
                `
    for(let i=0; i < clist.length ; i++){
        if (clist[i].periodo == periodo) {
            pagHTML += `
                <tr>
                    <td>${clist[i].id}</td>
                    <td>
                        <a href="/compositores/${clist[i].id}">
                            ${clist[i].nome}
                        </a>
                    </td>
                    <td>
                        [<a href="/compositores/edit/${clist[i].id}">Edit</a>][<a href="/compositores/delete/${clist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
        }
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-black">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/">Voltar</a>]</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}


exports.compositorFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Formulário de Compositor</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-black">
                    <h2>Formulário de Compositor</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadados</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>Biografia</label>
                        <input class="w3-input w3-round" type="text" name="bio"/>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="date" name="dataNasc"/>
                        <label>Data de Óbito</label>
                        <input class="w3-input w3-round" type="date" name="dataObito"/>
                        <label>Período</label>
                        <input class="w3-input w3-round" type="text" name="periodo"/>
                    </fieldset> 
                    <br/>
                    <button class="w3-btn w3-grey w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-black">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/compositores">Voltar</a>]</h5>
                </footer>
            
            </div>
    `
}

exports.compositorFormEditPage = function(c, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Formulário de edição do compositor</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-black">
                    <h2>Formulário de edição do compositor</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadados</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${c.id}"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${c.nome}"/>
                        <label>Git</label>
                        <input class="w3-input w3-round" type="text" name="bio" value="${c.bio}"/>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="date" name="dataNasc" value="${c.dataNasc}"/>
                        <label>Data de Óbito</label>
                        <input class="w3-input w3-round" type="date" name="dataObito" value="${c.dataObito}"/>
                        <label>Período</label>
                        <input class="w3-input w3-round" type="text" name="periodo" value="${c.periodo}"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-grey w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-black">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/compositores">Voltar</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

// ---------------Compositor's Page--------------------------------
// Change and adapt to current dataset...
exports.compositorPage = function( compositor, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Compositor: ${compositor.Id}</title>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-black">
                <h1>Compositor ${compositor.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${compositor.nome}</li>
                    <li><b>Biografia: </b> ${compositor.bio}</li>
                    <li><b>Data de Nascimento: </b> ${compositor.dataNasc}</li>
                    <li><b>Data de Óbito: </b> ${compositor.dataObito}</li>
                    <li><b>Período: </b> ${compositor.periodo}</li>
                </ul>
            </div>
            
            <footer class="w3-container w3-black">
                <address>Gerado por EngWeb2024 em ${d} - [<a href="/compositores">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}


// PERIODOS ------------------------------------------------------------------------

exports.periodosListPage = function(plist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Períodos</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-black">
                    <h1>Períodos
                    <a class="w3-btn w3-round w3-grey" href="/periodos/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Nome</th>
                            <th>Actions</th>
                        </tr>
                `
    for(let i=0; i < plist.length ; i++){
        pagHTML += `
                <tr>
                    <td>${plist[i].id}</td>
                    <td>
                        <a href="/periodos/${plist[i].id}">
                            ${plist[i].nome}
                        </a>
                    </td>
                    <td>
                        [<a href="/periodos/edit/${plist[i].id}">Edit</a>][<a href="/periodos/delete/${plist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-black">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/">Voltar</a>]</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}


exports.periodoFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Formulário de Período</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-black">
                    <h2>Formulário de Período</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadados</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                    </fieldset> 
                    <br/>
                    <button class="w3-btn w3-grey w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-black">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/periodos">Voltar</a>]</h5>
                </footer>
            
            </div>
    `
}

exports.periodoFormEditPage = function(c, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Formulário de edição do período</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-black">
                    <h2>Formulário de edição do período</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadados</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${c.id}"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${c.nome}"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-grey w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-black">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/periodos">Voltar</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

// ---------------Periodo's Page--------------------------------
// Change and adapt to current dataset...
exports.periodoPage = function( periodo, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Periodo: ${periodo.Id}</title>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-black">
                <h1>Periodo ${periodo.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${periodo.nome}</li>
                </ul>
            </div>
            
            <footer class="w3-container w3-black">
                <address>Gerado por EngWeb2024 em ${d} - [<a href="/periodos">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}


// -------------- Error Treatment ------------------------------
exports.errorPage = function(errorMessage, d){
    return `
    <html>
    <head>
        <title>Error</title>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
        <div class="w3-card-4">
            <header class="w3-container w3-black">
                <h1>Erro</h1>
            </header>
            
            <p>${d}: Error: ${errorMessage}</p>

            <footer class="w3-container w3-black">
                <address>Gerado por EngWeb2024 em ${d} - [<a href="/">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
}