import xml.etree.ElementTree as ET
import os
import re


pasta = '/home/marta/Desktop/Marta/EW/EngWeb2024/TPC1/MapaRuas-materialBase/texto'

ficheiros = os.listdir(pasta)

ruas = []
conteudo = ""

def chaveOrd(rua):
    return re.match(r" *(.+)",rua.find('.//meta/nome').text).group(1)

for arquivo in ficheiros:
    path = os.path.join(pasta, arquivo)
    file = ET.parse(path)
    rua = file.getroot()
    ruas.append(rua)
    
ruas.sort(key= chaveOrd)

for rua in ruas:
    nome = rua.find('.//meta/nome').text
    id = rua.find('.//meta/número').text
    
    conteudo += f"""
                <li>
                    <a href="rua{id}.html"> {nome} </a>
                </li>
    """

preHTML = """
<!DOCTYPE html>
<html>
    <head>
        <title>Lista das Ruas</title>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="stylesheet" href="w3.css">
        <meta charset="utf-8"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-green" style="text-align: center;">
                <h3>Lista das Ruas</h3>
            </header>

            <div class="w3-container" class="background-image-container" style="width: 100%; margin: 0 auto; background-image: url('/home/marta/Desktop/Marta/EW/EngWeb2024/TPC1/MapaRuas-materialBase/mapa-site/background.webp'); background-size: cover; background-position: center;">
                <ul class="w3-ul w3-card-4" style="width: 40%; margin: 0 auto;">
"""

posHTML = """
                </ul>
            </div>

            <footer class="w3-container w3-green" style="text-align: center;">
                <h5> Generated by Marta Gonçalves::EngWeb2024 </h5>
            </footer>
        </div>
    </body>
</html>
"""

pagHTML = preHTML + conteudo + posHTML

f = open('/home/marta/Desktop/Marta/EW/EngWeb2024/TPC1/MapaRuas-materialBase/mapa-site/indexruas.html', 'w')
f.write(pagHTML)
f.close()