import xml.etree.ElementTree as ET
import os
import re

pasta = '/home/marta/Desktop/Marta/EW/EngWeb2024/TPC1/MapaRuas-materialBase/texto'

ficheiros = os.listdir(pasta)

def imagens_antigas(corpo):
    imagens = ""
    for figura in corpo.findall('figura'):
        imagens += f"<img src=\"{figura.find('imagem').attrib['path']}\" alt=\"{figura.find('legenda').text}\" style=\"width: 90%;\"/>\n"

    return imagens

def imagens_novas(nome,id):
    #nome_maiusculas = re.sub(r" ([a-z])", lambda x: x.group(1).upper(), nome)
    nome_sem_espacos = re.sub(r" ","",nome)
    imagens = f"<img src=\"../atual/{id}-{nome_sem_espacos}-Vista1.JPG\" alt=\"{id} - {nome} - Vista 1\" style=\"width: 45%;\"/>\n<img src=\"../atual/{id}-{nome_sem_espacos}-Vista2.JPG\" alt=\"{id} - {nome} - Vista 2\" style=\"width: 45%;\"/>\n"
    return imagens

def infos(corpo):
    descricao = ""
    for paragrafo in corpo.findall('para'):
        para_text = ''.join(ET.tostring(e, encoding='unicode', method='text') for e in paragrafo.iter())
        descricao += f"<p>{para_text}</p>\n"
    
    return descricao
        
def lista_casas(corpo):
    lista_de_casas = """
        <div class="w3-container">
            <ul class="w3-ul">
    """

    lista = corpo.find('lista-casas')
    if lista is not None:
        for casa in lista.findall('casa'):
            numero = casa.find('número').text if casa.find('número') is not None else '???'
            enfiteuta = casa.find('enfiteuta').text if casa.find('enfiteuta') is not None else '???'
            foro = casa.find('foro').text if casa.find('foro') is not None else '???'
            descricao = infos(casa.find('desc')) if casa.find('desc') is not None else '???'

            lista_de_casas += f"""
                <li>
                    <table>
                        <tr>
                            <td><b>Número</b></td> <td>{numero}</td>
                        </tr>
                        <tr>
                            <td><b>Enfiteuta</b></td> <td>{enfiteuta}</td>
                        </tr>
                        <tr>
                            <td><b>Foro</b></td> <td>{foro}</td>
                        </tr>
                        <tr>
                            <td><b>Descrição</b></td> <td>{descricao}</td>
                        </tr>
                    </table>
                </li>
            """
    
    lista_de_casas += """
            </ul>
        </div>
    """
    return lista_de_casas

for arquivo in ficheiros:
    path = os.path.join(pasta, arquivo)
    file = ET.parse(path)

    rua = file.getroot()
    nome = rua.find('.//meta/nome').text
    id = rua.find('.//meta/número').text
    corpo = rua.find('corpo')

    print(nome)

    f = open(f'/home/marta/Desktop/Marta/EW/EngWeb2024/TPC1/MapaRuas-materialBase/mapa-site/rua{id}.html', 'w')
    pagHTML = f"""
    <html>
        <head>
            <title>{nome}</title>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="stylesheet" href="w3.css">
            <meta charset="utf-8"/>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-green">
                    <h3>{nome}</h3>
                </header>

                <div>
                    <h3>Imagens antigas:</h3>
                    {imagens_antigas(corpo)}
                </div>

                <div>
                    <h3>Imagens atuais:</h3>
                    {imagens_novas(nome,id)}
                </div>

                <div>
                    <h3>Descrição:</h3>
                    {infos(corpo)}
                </div>

                <div>
                    <h3>Lista das casas</h3>
                    {lista_casas(corpo)}
                </div>

                <footer class="w3-container w3-green">
                    <h5> Generated by Marta Gonçalves::EngWeb2024 </h5>
                    <address>
                        <a href="indexruas.html">Voltar ao índice</a>
                    </address>
                </footer>
            </div>
        </body>
    </html>
    """
    f.write(pagHTML)
    f.close()
