import json

f = open("emd.json")
bd = json.load(f)
f.close()

for e in bd:
    f = open('./emdSite/emd'+ str(e['_id']) + '.html', 'w')
    pagHTML = f"""
    <html>
        <head>
            <title>Exame Médico Desportivo: {e['nome']['primeiro']} {e['nome']['último']}</title>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="stylesheet" href="w3.css">
            <meta charset="utf-8"/>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h3>Exame Médico Desportivo: {e['nome']['primeiro']} {e['nome']['último']}</h3>
                </header>

                <div class="w3-container">
                    <table>
                        <tr>
                            <td><b>Data do EMD</b></td> <td>{e['dataEMD']}</td>
                        </tr>
                        <tr>
                            <td><b>Idade</b></td> <td>{e['idade']}</td>
                        </tr>
                        <tr>
                            <td><b>Género</b></td> <td>{e['género']}</td>
                        </tr>
                        <tr>
                            <td><b>Morada</b></td> <td>{e['morada']}</td>
                        </tr>
                        <tr>
                            <td><b>Modalidade</b></td> <td>{e['modalidade']}</td>
                        </tr>
                        <tr>
                            <td><b>Clube</b></td> <td>{e['clube']}</td>
                        </tr>
                        <tr>
                            <td><b>Email</b></td> <td>{e['email']}</td>
                        </tr>
                        <tr>
                            <td><b>Atleta federado</b></td> <td>{e['federado']}</td>
                        </tr>
                        <tr>
                            <td><b>Resultado do EMD</b></td> <td>{e['resultado']}</td>
                        </tr>
                    </table>
                </div>

                <footer class="w3-container w3-purple">
                    <h5> Generated by EMDApp::EngWeb2024 </h5>
                    <address>
                        <a href="index.html">Voltar ao índice</a>
                    </address>
                </footer>
            </div>
        </body>
    </html>
    """
    f.write(pagHTML)
    f.close()
